repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt (format)
        entry: gofmt -s -w
        language: system
        types: [go]

      - id: goimports
        name: goimports (organize imports)
        entry: goimports -w
        language: system
        types: [go]

      - id: go-vet
        name: go vet (static checks)
        entry: bash -c 'go vet ./...'
        language: system
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint (linters)
        entry: bash -c 'golangci-lint run'
        language: system
        pass_filenames: false
